name: contacts_pcsb
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^0.23.0
  url_launcher:
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/hackerman.jpg
    - assets/linkedin.png
    - assets/github.png
    - assets/gmail.jpg
    - assets/gmailnew.png
    - assets/imagegmail.png
    - assets/gmailfinal.png
