List<Map<String, dynamic>> dataList = [
  {
    "Email": "cschinmay777@gmail.com",
    "Name": "Chinmay Choudhary",
    "Gmail": "cschinmay777@gmail.com",
    "Mobileno": "9860267312",
    "Position": "App Head",
    "GitHub": "https://github.com/cschinmay777",
    "Linkedin": "https://www.linkedin.com/in/chinmay-choudhary-496968204",
    "Profilepic":
        "https://drive.google.com/open?id=1OnauckXbJbjqMCc6b0KuDlhez8S2qPqf",
  },
  {
    "Email": "badjatesoham@gmail.com",
    "Name": "Soham Badjate",
    "Gmail": "badjatesoham@gmail.com",
    "Mobileno": "9028031200",
    "Position": "Vice-Chairperson",
    "GitHub": "https://github.com/Soham1609",
    "Linkedin": "https://www.linkedin.com/in/soham-badjate-137870218",
    "Profilepic":
        "https://drive.google.com/open?id=1VNs2KK2hsZXVnuaoeACZUVFsKw_jObzc",
  },
  {
    "Email": "sahilckothari94@gmail.com",
    "Name": "Sahil Kothari",
    "Gmail": "sahilckothari94@gmail.com",
    "Mobileno": "9607482954",
    "Position": "Blockchain Head",
    "GitHub": "https://github.com/sahil-kothari",
    "Linkedin": "https://www.linkedin.com/in/sahil-kothari94",
    "Profilepic":
        "https://drive.google.com/open?id=19kcSir59a4N4Ez9zipmT7YWZhhNbK9SL",
  },
  {
    "Email": "anandbhalerao.l.a3b@gmail.com",
    "Name": "Anand Bhalerao",
    "Gmail": "anandbhalerao.l.a3b@gmail.com",
    "Mobileno": "9175799277",
    "Position": "App Head",
    "GitHub": "https://github.com/Anand-Avinash-Bhalerao",
    "Linkedin": "https://www.linkedin.com/in/anand-bhalerao-0b69451bb",
    "Profilepic":
        "https://drive.google.com/open?id=1RLEOUQUKEUYoBinzOaYsz9Zm08TlR3h2",
  },
  {
    "Email": "www.abhishek3jadhav@gmail.com",
    "Name": "Abhishek Jadhav",
    "Gmail": "www.abhishek3jadhav@gmail.com",
    "Mobileno": "7030405299",
    "Position": "Web Head",
    "GitHub": "https://github.com/AbhishekJadhav2002",
    "Linkedin": "https://www.linkedin.com/in/AbhishekJadhav2002",
    "Profilepic":
        "https://drive.google.com/open?id=1HIgkmkSFSJPsV_tQmOkXb-UEqdr-iiPz",
  },
  {
    "Email": "atharvanagmoti@gmail.com",
    "Name": "Atharva Nagmoti",
    "Gmail": "atharvanagmoti@gmail.com",
    "Mobileno": "8668452969",
    "Position": "ML Head",
    "GitHub": "https://github.com/atharvanagmoti20",
    "Linkedin": "https://www.linkedin.com/in/atharva-nagmoti",
    "Profilepic":
        "https://drive.google.com/open?id=1qdk_CyWBY5ewJ1woEOHnAps1kJPTpKI2",
  },
  {
    "Email": "abhimsound@gmail.com",
    "Name": "Abhishek Soundalgekar",
    "Gmail": "abhimsound@gmail.com",
    "Mobileno": "7020458963",
    "Position": "Event Coordinator",
    "GitHub": "https://github.com/ABHISHEKSOUNDALGEKAR",
    "Linkedin": "https://www.linkedin.com/in/abhishekmsoundalgekar/",
    "Profilepic":
        "https://drive.google.com/open?id=13wvlqvcavLby68WJZ3Gkpb0XTdkGROCh",
  },
  {
    "Email": "shivakumar.ranade@gmail.com",
    "Name": "Shivakumar Ranade",
    "Gmail": "shivakumar.ranade@gmail.com",
    "Mobileno": "8530011069",
    "Position": "Web Head",
    "GitHub": "https://github.com/Shivakumar-pyt",
    "Linkedin": "https://www.linkedin.com/in/shivakumar-ranade-96a51b227/",
    "Profilepic":
        "https://drive.google.com/open?id=10_BYE42_DJ0W7dGyUMrBJv75Uf3fwhUE",
  },
  {
    "Email": "mansigundre1@gmail.com",
    "Name": "Mansi Gundre",
    "Gmail": "mansigundre1@gmail.com",
    "Mobileno": "784301258",
    "Position": "CTH",
    "GitHub": "https://github.com/mansi0829",
    "Linkedin": "https://www.linkedin.com/in/mansi-gundre/",
    "Profilepic":
        "https://drive.google.com/open?id=1y7DUnueylCVHxerKSk-ifcl6hdXVBY3Z",
  },
  {
    "Email": "ameya.a.dhake@gmail.com",
    "Name": "Ameya Dhake",
    "Gmail": "ameya.a.dhake@gmail.com",
    "Mobileno": "9075009347",
    "Position": "Video Editing Head",
    "GitHub": "https://github.com/Ameya6514",
    "Linkedin": "https://www.linkedin.com/in/ameya-dhake-a69b2b218",
    "Profilepic":
        "https://drive.google.com/open?id=1mISaPs2QYDGhb2hM95cucYAOJETPwBtC",
  },
  {
    "Email": "reva.dalal.197167@gmail.com",
    "Name": "Reva Dalal",
    "Gmail": "reva.dalal.197167@gmail.com",
    "Mobileno": "8669666025",
    "Position": "Marketing and Publicity Director",
    "GitHub": "Na",
    "Linkedin":
        "htts://www.linkedin.com/in/reva-dalal-200b44250?trk=contact-info",
    "Profile pic":
        "https://drive.google.com/open?id=1GtbiwXUDiebpIheo3QA-pyT5swqceORS",
  },
  {
    "Email": "shreyal.nagle1@gmail.com",
    "Name": "Shreyal Nagle",
    "Gmail": "shreyal.nagle1@gmail.com",
    "Mobileno": "9970796471",
    "Position": "Marketing Head",
    "GitHub": "NA",
    "Linkedin": "https://www.linkedin.com/in/shreyal-nagle-1491791bb",
    "Profilepic":
        "https://drive.google.com/open?id=1X2FyYmzcBio17Q6EP1TpKJ-_VBc8gbPf",
  },
  {
    "Email": "29piyushbora@gmail.com",
    "Name": "Piyush Bora",
    "Gmail": "29piyushbora@gmail.com",
    "Mobileno": "7666066207",
    "Position": "Joint Secretary",
    "GitHub": "https://www.github.com/Piyush-Bora",
    "Linkedin": "https://www.linkedin.com/in/piyushbora",
    "Profilepic":
        "https://drive.google.com/open?id=1_5XgeIMBLnM6Nj_5ubTrPnFzKJ2NPgwR",
  },
  {
    "Email": "thoratdhiraj444@gmail.com",
    "Name": "Dhiraj Thorat",
    "Gmail": "dpthorat85@gmail.com",
    "Mobileno": "8552041489",
    "Position": "Treasurer",
    "GitHub": "https://github.com/Dhirajpt1234",
    "Linkedin": "https://www.linkedin.com/in/dhiraj-thorat-073970215",
    "Profilepic":
        "https://drive.google.com/open?id=1O1EeTmXktOyTxCGV5Vh3c84DVHNmKzVK",
  },
  {
    "Email": "avora9721@gmail.com",
    "Name": "Aryan Vora",
    "Gmail": "avora9721@gmail.com",
    "Mobileno": "8983134579",
    "Position": "Marketing Head",
    "GitHub": "https://github.com/aryan9721",
    "Linkedin": "https://www.linkedin.com/in/aryan9721/",
    "Profilepic":
        "https://drive.google.com/open?id=1sa4h1U7pmvgOYyDMbHsoP3epSjyzUuLW",
  },
  {
    "Email": "tanishapareek2002@gmail.com",
    "Name": "Tanisha Pareek",
    "Gmail": "tanishapareek2002@gmail.com",
    "Mobileno": "9175643973",
    "Position": "Coding Circle Director",
    "GitHub": "https://github.com/TANISHA-P",
    "Linkedin": "https://www.linkedin.com/in/tanishapareek/",
    "Profilepic":
        "https://drive.google.com/open?id=1aegLYCuh0DXYocCIFwCbjsAIgRK0DTWB",
  },
  {
    "Email": "nvaibhavmahajan00@gmail.com",
    "Name": "Vaibhav Mahajan",
    "Gmail": "nvaibhavmahajan00@gmail.com",
    "Mobileno": "7038522474",
    "Position": "Sponsorship Head",
    "GitHub": "https://github.com/VNM02",
    "Linkedin": "https://www.linkedin.com/in/vaibhav-mahajan-403979212/",
    "Profilepic":
        "https://drive.google.com/open?id=1f48S1Zcr4YH2XesYYv_RXHM402BYv9oQ",
  },
  {
    "Email": "ugutaman786@gmail.com",
    "Name": "Aman Mugut",
    "Gmail": "ugutaman786@gmail.com",
    "Mobileno": "9689072736",
    "Position": "App head",
    "GitHub": "https://github.com/amanmugut",
    "Linkedin": "https://www.linkedin.com/in/aman-mugut-b43673221/",
    "Profilepic":
        "https://drive.google.com/open?id=1QmhklwLsXzFcgjie88vgKG4SeKrd0EGd",
  },
  {
    "Email": "aishnaviraut2203@gmail.com",
    "Name": "Vaishnavi Raut",
    "Gmail": "aishnaviraut2203@gmail.com",
    "Mobileno": "7448044859",
    "Position": "Coding circle - coordinator",
    "GitHub": "https://github.com/VaishnaviRaut123",
    "Linkedin": "https://www.linkedin.com/in/vaishnavi-raut-4a0228224/",
    "Profilepic":
        "https://drive.google.com/open?id=1o3PvU6Mu5iI1FVokwzXusABsKLa1pSas",
  },
  {
    "Email": "yashpkulkarni@gmail.com",
    "Name": "Yash Kulkarni",
    "Gmail": "yashpkulkarni@gmail.com",
    "Mobileno": "8329448702",
    "Position": "Joint secretary of event management and content",
    "GitHub": "https://github.com/Yash-kkulkarni",
    "Linkedin": "https://www.linkedin.com/in/yash-kulkarni-218223218/",
    "Profilepic":
        "https://drive.google.com/open?id=1pY-TnaAGwHjAAu_zAh11UR60S85Ohhjm",
  },
  {
    "Email": "rajshende220802@gmail.com",
    "Name": "Raj Shende",
    "Gmail": "rajshende220802@gmail.com",
    "Mobileno": "9021716500",
    "Position": "Web Head",
    "GitHub": "https://github.com/shenderaj9021",
    "Linkedin": "https://www.linkedin.com/in/raj-shende-350718204/",
    "Profilepic":
        "https://drive.google.com/open?id=1Is6cG1cYxFLP2SCWyePQ6TpOnxQyfidR",
  },
];
